[package]
authors = ["Peter Huene <peter@huene.dev>"]
edition = "2018"
name = "lists-main"
publish = false
version = "0.1.0"

[dependencies]
cosmian-wit-bindgen-rust = {path = "../../../../rust-wasm"}
