[package]
name = "wasmlink-cli"
version = "0.1.0"
authors = ["Peter Huene <peter@huene.dev>"]
edition = "2018"

[[bin]]
name = "wasmlink"
path = "src/bin/wasmlink.rs"

[dependencies]
wasmlink = { path = "../wasmlink" }
cosmian-wit-parser = { path = "../parser" }
anyhow = "1.0.40"
structopt = "0.3.21"
log = "0.4.14"
env_logger = "0.8.3"
wat = "1.0.37"
