[package]
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"
name = "wit-bindgen-gen-wasmtime"
version = "0.1.0"

[lib]
doctest = false
test = false

[dependencies]
cosmian-wit-bindgen-gen-core = {path = '../gen-core', version = '0.1.0'}
cosmian-wit-bindgen-gen-rust = {path = '../gen-rust', version = '0.1.0'}
heck = "0.3"
structopt = {version = "0.3", default-features = false, optional = true}

[dev-dependencies]
anyhow = "1.0"
test-helpers = {path = '../test-helpers', features = ['wit-bindgen-gen-wasmtime']}
wasmtime = "0.32.0"
wasmtime-wasi = "0.32.0"
wit-bindgen-wasmtime = {path = '../wasmtime', features = ['tracing', 'async']}

[features]
witx-compat = ['cosmian-wit-bindgen-gen-core/witx-compat']
